### ISSUE TITLE
Add support for values and tuples

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#11]
Values is very useful for determining min/max, and total count of values (could also be shown in facets). Tuples is necessary for showing co-occurrences (n-way)..

**Comment by grtjn** [comment]
There is support for values in MLRest, but that doesn't automatically take selected facets into consideration. That could be useful.

**Comment by grtjn** [comment]
I'm having a look at this. I like what was done with showMoreFacets. Would be interesting to do that for the aggregates as well. In addition to a generic values/tuples endpoint of course..

**Comment by joemfb** [comment]
I actually have this mostly done. I'll try to get a PR out soon, and you can compare with your approach.

**Comment by grtjn** [comment]
OK, I'll just focus on getting aggregates based on facetName then.. :)

**Comment by grtjn** [comment]
I'll create a separate ticket for that.

**Comment by joemfb** [comment]
See https://github.com/joemfb/ml-search-ng/tree/values for the current progress. Needs a rebase at least.

**Comment by grtjn** [comment]
The compare looks reasonably clean https://github.com/joemfb/ml-search-ng/compare/values..
