### ISSUE TITLE
improved bundled facet templates

### ISSUE THREAD

**Issue by joemfb** [joemfb/ml-search-ng#24]
facet counts are (awkwardly) included in links

**Comment by grtjn** [comment]
How about a more/less feature? Show 5 facet values by default, increment by 5. Bonus points if it does a round-trip to pull extra values.

**Comment by grtjn** [comment]
Maybe provide pre-built templates to show chiclets and facets separately (ml-facet template="chiclets" vs template="facets").

**Comment by grtjn** [comment]
Also the default behavior is to hide facets if one value is selected, but sometimes values can co-occur, and you should show the alternatives (and maybe only hide the selected one, or show it with a remove link)..

**Comment by joemfb** [comment]
Both of those features should be available in the bundled templates. The default template is separate facet/chiclet. Both the default and the inline template support facets will multiple values in a document. 

Here's an example of multiple values with the inline template (note the "salary" facet): http://paycheck.demo.marklogic.com/search?facets=salary:%22less%20than%20$100K%22

**Comment by joemfb** [comment]
As for more/less with a roundtrip, I'm interested. You'd have to pass the a reference to the relevant MLSearchInstance into the directive. Do you have a particular application in mind?

**Comment by grtjn** [comment]
Maybe I should have checked whether or not we are using the latest. I'll have a look..

**Comment by grtjn** [comment]
More/less: ultimately, think of markmail where you can pull open a modal with full list of facet values. Passing in search context, maybe. Callbacks to make it go through ctrl also possible?


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Joseph Bryan <notifications@github.com> 
Datum: 13-04-2015  19:08  (GMT+01:00) 
Aan: joemfb/ml-search-ng <ml-search-ng@noreply.github.com> 
Cc: Geert <geert.josten@xs4all.nl> 
Onderwerp: Re: [ml-search-ng] improved bundled facet templates (#24) 
 
As for more/less with a roundtrip, I'm interested. You'd have to pass the a reference to the relevant MLSearchInstance into the directive. Do you have a particular application in mind?

**Comment by grtjn** [comment]
Meh, slush template is still pointing to version 0.0.6, that is old..
