### ISSUE TITLE
What is best way to handle multiple search contexts with params?

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#28]
The function fromFacetParam in ml-search.service.js looks for .type property of facets, but throws an error if the facet name mentioned in request param doesn't exist in search context at hand. This typically occurs when you have multiple search contexts, and they both try to read selected facets from request params.

It would help if unknown facet names would be ignored. I don't expect much name conflicts (in this particular case)..

**Comment by joemfb** [comment]
Are you using more-than-one searchContext for facets?

**Comment by grtjn** [comment]
No, we simply have multiple search options, each tuned for a different subset of the data, and have a different search context for each. And because we combine info within one ctrl, we have access to it in one ctrl, on one url.

We bypassed the issue for the moment, by disabling this parameter stuff.

Maybe you could solve it by prefixing the request params with something that identifies the searchcontext, or allow support for something like that. Something like ?all:q=xx&other:q=yy, or something more terse maybe. But as said, bit more robust code would already help a lot..

**Comment by joemfb** [comment]
So your facets are generated from a union of search options / searchContexts? And a particular URL facet-parameter could refer to any of the searchContexts?

**Comment by grtjn** [comment]
They are handled and shown separately, but effectively reside on one page. We have three tabs, one with results and facets from first context, one with same of the other, and a third that shows charts with a mix of both contexts. The qtext is kind of shared, but facets of course don't overlap. So a facet-param would match with just one of either searchContexts. Unfortunately, ml-search throws an error if it finds a facet-param that doesn't match any of the facets from first context, and never reaches second context..

**Comment by joemfb** [comment]
Thanks, for the details; that makes sense. I think it makes sense for `MLSearchContext.fromFacetParam` to ignore unknown facets, instead of fail with an error.

However, I do think it would be most robust to pre-process the URL params in your controller, and only send a subset of the params to each searchContext. If both searchContexts were to end up with facets with the same name, that would cause real problems.

**Comment by grtjn** [comment]
yes, hence the idea of doing something with prefixes. Unfortunately, the search context is kind of eager to push its config to the url directly by itself, to bit difficult to keep under control self. So, maybe it should not do that, and rely on something like a `searchContext.toFacetParam` kind of call, or allow configuration to prefix the request param names..

**Comment by joemfb** [comment]
The searchContext only reads the URL params, it doesn't write to them: see [`mlSearch.getParams()`](https://github.com/joemfb/ml-search-ng/blob/def88d962b096707fddfa82b0102770dc95f26c9/src/ml-search.service.js#L657) and [`mlSearch.fromParams`](https://github.com/joemfb/ml-search-ng/blob/def88d962b096707fddfa82b0102770dc95f26c9/src/ml-search.service.js#L716). [`mlSearch.locationChange()`](https://github.com/joemfb/ml-search-ng/blob/def88d962b096707fddfa82b0102770dc95f26c9/src/ml-search.service.js#L795) is just a convenience function so you know when to update the params. In the default search-ctrl for the slush generator, the URL params are updated in [`updateSearchResults()`](https://github.com/marklogic/slush-marklogic-node/blob/0901120d68c04f508bfa9b403e73dcedc9b34aaa/app/templates/ui/app/search/search-ctrl.js#L44), which seems like a good approach. With some custom logic, it should be pretty straightforward to prefix URL params on a per-context basis, and then route the params to the appropriate searchContext (and strip the prefix).

**Comment by grtjn** [comment]
You are right, my bad. That behavior is in search-ctrl, not in ml-search. How about a bit of convenience where you can provide a prefix to getParams and fromParams call?

**Comment by joemfb** [comment]
Would it make more sense to have the prefix be part of the searchContext config, instead of a per-call parameter? Something like

```
var mlSearch = searchFactory.newContext({
  params: { prefix: 'blah' }
});

mlSearch.setText('hi')
.setPage(3)
.getParams()
// =>
{
  "blah:q": "hi",
  "blah:page": 3
}```

If `params.prefix` is set,  `mlSearch.fromParams()` would only pull prefix'd params. `params.prefix` would default to `null`.

What do you think?

**Comment by joemfb** [comment]
Thinking through this use-case, do facet/constraint names also need to be prefixed?

Ex:

```
var mlSearch = searchFactory.newContext({
  params: {
    prefix: 'blah',
    prefixSeparator: '*_*'
  }
});

mlSearch.selectFacet('color', 'red')
.getParams()
// =>
{
  "blah*_*f": "blah*_*color:red"
}```

Or is a prefix on the param name sufficient:

```
{
  "blah*_*f": "color:red"
}```

**Comment by joemfb** [comment]
I went ahead and skipped the facet-name prefix; I can't think of a use-case where it's necessary.

@grtjn, can you test the changes in the pull-request, and see if it fulfills your requirements? I'll add a test with multiple concurrent mlSearch instances when I can.

**Comment by grtjn** [comment]
I think it makes sense to prefix facet-names as well. The issue in our case arose because of fromParams failing due to request-params pointing to facets from a different search context. You can rely on the silent ignore there, but having a feature to isolate those properly makes sense to me..

**Comment by grtjn** [comment]
Have you considered writing the params as pref:name=value, where you use 'f' or 'ml' as default prefix?

`?ml:q=blah&ml:color=red&..`

Nothing stops you by the way from using two colons in param names: `ml:f:color=red`

**Comment by joemfb** [comment]
There's two changes that support your original use-case: unknown facet-names are ignored, not an error; and the facets param is prefix-able.

In this example the mlSearch instance for `prefix2` will ignore both `color:red` and `foo:bar` due to the presence of `prefix1`. If we assume the facet `foo` is unknown to the `prefix2` mlSearch instance, than `foo:baz` is also ignored, without error.

```
{
  "prefix1:f": [
    "color:red",
    "foo:bar"
  ],
  "prefix2:f": [
    "color:blue",
    "foo:baz"
}
```

I'll let you know once I've added a test specifically demonstrating this.

**Comment by joemfb** [comment]
@grtjn, I've added a test demonstrating `getParams()` and `fromParams()` with three concurrent search contexts: https://github.com/joemfb/ml-search-ng/commit/df475937f8fdfc047b4792bcd92e9c3fb42280fc

Can you take a look at that commit, and see if the `cleanup-params` branch works for your use-case?

**Comment by grtjn** [comment]
I will definitely take a look, but afraid that will have to wait till later. Bit short on spare time at the moment..

**Comment by joemfb** [comment]
I've pulled the trigger on #31. Please open a new issue if you find it to be insufficient.
