### ISSUE TITLE
Suggestion: expose ml-duration as a filter

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#30]
Have you considered exposing ml-duration as filter instead of as directive? (Or maybe have directive use filter) Not sure it provides real benefits, but sounds more logical. Bit like date filter, and such..

**Comment by joemfb** [comment]
I'm not sure how the filter could be used in angular expressions (outside of `ng-repeat`, where new variables can be bound). The parsing code in `ml-duration` emits a new object, which would need to be referenced to be used.

A filter could be used easily enough in JS, but a service would be even easier. Are there other string formats commonly parsed from REST API responses that could be grouped together into a parsing service?

**Comment by grtjn** [comment]
Using filters in expressions is really simple and convenient: `{{ myvar | myfilter:arg1:arg2:arg3 }}`

The toLimit filter works both in ng-repeat and in expressions as above. You only need to keep in mind that in ng-repeat you will receive an array, and in the second you receive one value. I am pretty sure the toString will make sure the duration object is rendered nicely. Maybe give it a try? Filters can be a lot of fun..

**Comment by joemfb** [comment]
I understand filters, but I don't see how one would help here. The output of the filter is an object, which you would need to reference in order to use (unless you wanted one property, in which case maybe `(duration | durationFilter).years` could work).

`ng-repeat` lets you bind a new scope variable from an angular expression, but that's pretty awkward if you only have one duration to process.

Can you add an example of you would use a filter to parse and display properties of a duration?

**Comment by grtjn** [comment]
I'd be already happy with just the default formatting of toString, but I could imagine one passing in a formatting string as param to durationFilter. Perhaps something like: "PT1D2H" | durationFilter:"%D day(s) %H hour(s)"?

**Comment by joemfb** [comment]
`toString()` just returns the original ISO duration, but a formatting string would be cool. It's a low priority for me, though, the directive as is gives all the same capabilities, and is just a little more verbose: https://github.com/joemfb/ml-search-ng/blob/master/src/templates/ml-metrics.html#L3.

Pull requests welcome!

**Comment by grtjn** [comment]
Interesting? https://github.com/oshai/angular-duration-filter

**Comment by grtjn** [comment]
Looking into this, and discovering code in previous link give me a different idea about formatting. A formatting string sounds nice, but you cannot really predict whether the xs:duration will contain seconds, hours, days, or whatever. And you probably want to flexibly ignore what is not relevant. So, I took the approach of a configurable formatting instead. You could do something like:

```html
  <span ng-show="showDuration">
    <span>in {{ metrics['total-time'] | duration }}.</span>
  </span>
```

Could be worthwhile migration duration stuff to ml-common-ng..
