### ISSUE TITLE
Non-clickable clear icon in ml-input fa template

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#34]
Used in demo-cat amongst others. You can type in a search term, and the icon appears nicely, but for some reason it refuses to respond to clicking. I have taken a brief look, but couldn't figure out what was going wrong. Could be as simple as clicking span's doesn't work, or maybe the callback function cannot be found?

**Comment by grtjn** [comment]
It looks trying to float something clickable over an input field is not going to work. In demo-cat I put it after the input field, instead of above. Looks less nice, but at least works. Would love to hear if there is a way to make it work after all..

**Comment by joemfb** [comment]
The `ml-input-fa` template works as-is in a handful of demos, so something else must be going wrong.

Do you have time to help me get setup with a recent version of demo-cat? I get errors trying to locally deploy the latest dev branch.

**Comment by grtjn** [comment]
Sharing screens would be a good idea i think, when would work for you?
