### ISSUE TITLE
Issue with annotateActiveFacets

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#39]
Observed in demo-cat with latest (0.0.12) ml-search-ng. Selected facets are not being marked. Maybe because we are using latest lodash (3.6.0). I had to rearrange the part inside if selected to:

```javascript
        if ( selected ) {
          _.forEach(
            _.filter(facet.facetValues, function(value) {
              return _.contains( selected.values, value.name );
            }),
            function(value) {
              facet.selected = value.selected = true;
            }
          );
        }
```

Maybe upgrade lodash dependency in ml-search-ng?

**Comment by joemfb** [comment]
Lodash 3 chaining is lazily evaluated, and incompatible with lodash 2. Appending `.run()` or `.value()` to the end of the chain would resolve this issue.

I've been working on the test suite; once I have good coverage, it'll be easy to upgrade dependencies

**Comment by grtjn** [comment]
My above code might work with both? Anyhow, I worked around it in demo-cat. I should have realized I cannot just upgrade to different major versions like that..

**Comment by joemfb** [comment]
I just went with `.value()`. Not as a clear as `.run()`, but it's no backwards/forwards compatible.
