### ISSUE TITLE
Different options for suggest

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#41]
We were struck by an issue that if you use no-results, /v1/suggest doesn't return suggestions either. We then wanted to override search options for /v1/suggest, but had to use monkey patching to get this working. A suggestOptions option on factory.newContext would make this easier.

```javascript
 var mlSearch = searchFactory.newContext({queryOptions:'no-results'});
          
      // Monkey patch mlSearch, to fix suggest
      mlSearch._suggest = mlSearch.suggest;
      mlSearch.suggest = function(qtext) {
        var _options = mlSearch.options.queryOptions;
        mlSearch.options.queryOptions = 'all';
        var result = mlSearch._suggest(qtext);
        mlSearch.options.queryOptions = _options;
        return result;
      };
```

**Comment by joemfb** [comment]
That's a good idea; I've been bit by the same problem.

**Comment by grtjn** [comment]
Extending mlSearch.suggest for this purpose is easy. Embedding custom search options for suggest into ml-remote-input and ml-input slightly more difficult. Looking into it..

**Comment by grtjn** [comment]
@joemfb, question:

I'd like to somehow provide suggest options to ml-remote-input. I could provide it directly to the directive (as an = binding attribute), or supply it through initCtrl somehow. What makes most sense you think?

**Comment by grtjn** [comment]
I had tried the attribute approach first, but not very practical on ml-remote-input. It is typically not within reach of SearchCtrl, so you would have to make that available, or put suggest options elsewhere. Neither makes sense.

Looking at the initCtrl approach, one way would be to provide suggestOptions as 5th param, or as part of 2nd param `model`. Another way would be to supply a suggest call-back as 5th param, but then you could ask yourself why passing in mlSearch as well, as it is only used to call mlSearch.suggest..

One last way could be that you wrap mlSearch, but that sounds inconvenient..

@joemfb any thoughts on this?

**Comment by joemfb** [comment]
Sorry for the delay on this. The general approach makes sense to me.

As for `ml-remote-input`, I actually have some updates that should make this easier. I'm deprecating `MLRemoteInputService.initCtrl()`, and providing an MLRemoteSearchController that will do the wiring. `initCtrl` makes too many assumptions, and is a really ugly and brittle API.

With a specific controller prototype for working with `ml-remote-input`, the suggest options could just be a controller property. In fact, that could be the pattern for the regular search controller as well.

How does that sound?

**Comment by grtjn** [comment]
Bit hard to picture without code, but yes it sounds good..

**Comment by joemfb** [comment]
That PR demonstrates what I have so far. If it makes, the resolution for this ticket can be built on top of that. (ie, `suggestOptions` as a property of the controller, automatically integrated for you)

**Comment by grtjn** [comment]
Well actually, just a suggestOptions in the searchCtrl is all we need! Let me redo all this, and clean up my PR..

**Comment by grtjn** [comment]
Much cleaner like this. I totally forgot you provide an mlSearch to remote-input that can hold all the details you want..
