### ISSUE TITLE
Bug in showMoreFacets stepping

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#45]
```javascript
var limit = start + step;
```

should be:

```javascript
var limit = start + step - 1;
```

**Comment by joemfb** [comment]
I merged your fix, but it broke the `showMoreFacets` tests... I should've thought've that.

Could you do an additional PR for those tests? Looks like an easy fix.

**Comment by grtjn** [comment]
I'll take a look as soon as I got a test working for getAggregates..

**Comment by grtjn** [comment]
By the way, maybe you can unmerge the PR? Not a biggy though..

**Comment by grtjn** [comment]
I included the test fixed into PR #57, if that is okay with you..

**Comment by joemfb** [comment]
Thanks, it looks good.
