### ISSUE TITLE
TransformMetadata breaks on error response

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#52]
It trips over these lines if result is null or undefined:

```javascript
      metadata = result.metadata;
      result.metadata = {};
```

Changing it into this fixes that:
```javascript
      result = result || {};
      metadata = result.metadata;
      result.metadata = {};
```

Perhaps it should not reach this code at all in case of error, but it at least makes it more robust..

**Comment by joemfb** [comment]
I'm curious; what type of error resulted in `null` or `undefined`, but still invoked the success callback? Or where you manually invoking `transformMetadata()`?

**Comment by grtjn** [comment]
I thought just a call to /v1/search with a faulty all.xml..

**Comment by joemfb** [comment]
I'll leave this open, 'cause I'd like to investigate further. The general pattern throughout this project is to not explicitly handle errors, but just pass them on in the Promise. I assumed they'd always fall through to the consumer (and even have some tests to verify that). Given all that, I'm surprised the success callback was invoked.

**Comment by grtjn** [comment]
Yeah, I think it is because either proxying of REST api itself returns a 200, while the body is an error message. Something like that. Error handling is suboptimal in the slush template in which I encountered this..

**Comment by joemfb** [comment]
Oh, I see. The older version of slush is the culprit. No need to keep this open; that would definitely invoke the callback.
