### ISSUE TITLE
Getting aggregates for facets

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#54]
Having seen showMoreFacets, we should pull a similar trick to get aggregates like min/max for facets. Would be super-useful for range sliders and date pickers for non-string facets..

**Comment by grtjn** [comment]
Actually, we could get aggregates for all facets. Aggregates `count`, `min`, and `max` are supported for all index types. Numeric ones also support aggregates like `sum`, `avg`, and things like `stddev`. I think these aggregates can be very useful for sliders, date pickers, and also for showing facets in charts..

Working on a PR..

**Comment by joemfb** [comment]
BTW, if you want to apply aggregates for each values individually, instead of across all values, checkout out https://github.com/joemfb/group-by and https://github.com/joemfb/analytics-query-browser.

**Comment by grtjn** [comment]
I was talking about aggregates on facets. I'll push my changes so you can see what I am after..

**Comment by joemfb** [comment]
I see. These overall facet values could then be worked into facet header displays, or something like that.

**Comment by grtjn** [comment]
Yes, all kinds of things. Show percentages instead of counts, set a min/max on date pickers and sliders, show an average in a chart, highlight things above or under avg, etc etc..
