### ISSUE TITLE
Make showMoreFacets return a promise

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#56]
It is now returning `this` to allow chaining, but it makes more sense to return a promise like `search`. You can then do something like:

```javascript
showMore: function showMore(facet, facetName, loading) {
    loading.loading = true;
    return mlSearch.showMoreFacets(facet, facetName, 50).then(function() {
        loading.loading = false;
    });
},
```

**Comment by joemfb** [comment]
A rewrite of this function is in progress, along with the values implementation.

**Comment by joemfb** [comment]
See https://github.com/joemfb/ml-search-ng/tree/values

**Comment by grtjn** [comment]
Excellent! You also switched to getStoredOptions, nice.

Small suggestion: https://github.com/joemfb/ml-search-ng/compare/values#diff-cefe6b0c1e10a0419b090ef97ccb03d0R1167, would be nice to getStoredOptions, and check if values config exists. If not, build one dynamically from facet config. Even better if you could use the function to get more values in 'pages' (using start/limit)..

**Comment by joemfb** [comment]
Check for a values config with the same name as the facet?

As for "pages", do you mean the ability to jump arbitrarily?

**Comment by grtjn** [comment]
I mean, check for values with the exact name first, otherwise look for facet with that name, and construct the values config dynamically.

pages: like showMoreFacets to not get them all (potentially many) in one blow, but more gradually..

**Comment by joemfb** [comment]
`showMoreFacets` takes a step parameter, so you can get the next `n` values.

**Comment by grtjn** [comment]
Sorry for the confusion, I was talking about the new `values` function..
