### ISSUE TITLE
Question regarding <style> in ml-input-fa

### ISSUE THREAD

**Issue by jenbreese** [joemfb/ml-search-ng#65]
Do we have to have the ~style~ in this file? The level of the selector's specificity makes it very hard to override and updating bower files is complicated.

**Comment by joemfb** [comment]
No, but the template absolutely needs those styles in some way. We could go all-in with LESS, and expect template users to import the LESS styles directly. We could also just distribute a CSS file. The selector's specificity was to avoid accidental collisions, but of course it makes it harder to override ...

Thoughts?

**Comment by joemfb** [comment]
For easy context, the template in question: https://github.com/joemfb/ml-search-ng/blob/master/src/templates/ml-input-fa.html

**Comment by jenbreese** [comment]
I see your point. I'd prefer if it was in it's own CSS file, then people can just include it in their files. If it isn't in the HTML, then the specificity isn't so bad because it will be easier to override since it won't be in such close proximity to the actual object.
