### ISSUE TITLE
Check for facet value existance fails for falsy values

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#67]
A facet value "no" is interpreted as falsy here (ml-facets.html):

```html
        <span ng-if="value.name">{{ value.name | truncate:truncateLength }}</span>
        <em ng-if="!value.name">blank</em>
```

I think it would be better to check value.name.length instead, or maybe also check for whitespace-only.

**Comment by grtjn** [comment]
Maybe this filter could be useful here: https://github.com/a8m/angular-filter#test

**Comment by joemfb** [comment]
I don't see how "no" could be falsy: `!!'no'` returns `true`. Could you add some more detail, or maybe a failing test?

**Comment by grtjn** [comment]
Well, we literally had a facetvalue 'no', and the facet display showed *blank* instead of 'no'

**Comment by joemfb** [comment]
Wow, it was deliberate, at least at one point: https://github.com/angular/angular.js/blob/fca7bcaf43af3a4501ea0727d48f606c58d76bcd/src/Angular.js#L961.

WTF, angular?

**Comment by joemfb** [comment]
replacing `<span ng-if="value.name">` with `<span ng-if="!!value.name">` should fix it. I'll try to get a failing test case first.

**Comment by grtjn** [comment]
:-D

**Comment by joemfb** [comment]
Could you find out what version of angular this happened for?

**Comment by grtjn** [comment]
Hmm. Nish was playing with slush. It must have been the 0.1.2 release or latest from github (minus one week perhaps). So 1.2 or 1.4..

**Comment by joemfb** [comment]
I can't reproduce on either, but I just pushed 111f54e. Please re-open if you see the same behavior once you're on a new release.

**Comment by Audarth** [comment]
Added in the change on my local, I believe I was using 0.1.2. It seems to resolve the bug and I now see "No" values so great job joe!
