### ISSUE TITLE
remove weeks from ml-duration

### ISSUE THREAD

**Issue by joemfb** [joemfb/ml-search-ng#70]
While [wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Durations) discusses weeks as valid ISO duration values, [xs:duration](http://www.w3.org/TR/2012/REC-xmlschema11-2-20120405/#duration) includes nothing about weeks. I have been unable to create a valid `xs:duration` including a week in XQuery.

Therefore, weeks should be removed from the `ml-duration` directive and `duration` filter

re #30, #53

**Comment by grtjn** [comment]
A search among the fn function yields:

```
fn:days-from-duration
fn:hours-from-duration
fn:minutes-from-duration
fn:months-from-duration
fn:seconds-from-duration
fn:subtract-dateTimes-yielding-dayTimeDuration
fn:subtract-dateTimes-yielding-yearMonthDuration
fn:years-from-duration
```

**Comment by joemfb** [comment]
So, invalid in XML, but potentially valid in other environments. Appears to be valid ISO 8601 ...

Probably safe to leave it.
