### ISSUE TITLE
Show more ignores buckets..

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#74]
To be expected I guess, given the implementation, but I have a bucketed facet, and I show the show more. If I click it, I get extra values, but those contain individual values, not more buckets.

I guess the only way to make that work is call /v1/search for that particular facet with an increased limit, instead of calling /v1/values..

**Comment by joemfb** [comment]
Yeah, we'd have to switch to /v1/search. Should still be able to get the offset values using `skip` and `limit` facet-options. There's lots of inconsistencies with the facets, I think the implementation needs some higher-level rethinking.

**Comment by grtjn** [comment]
Can we as a temp solution suppress 'show more' for such bucketed facets? I think you can detect buckets from response. And if so, you could set the `displayingAll` flag perhaps?
