### ISSUE TITLE
Show more ignores frequency-order

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#75]
I was convinced this was working, but I have a slush vanilla app with the larger sample data set to which I added a path index for tags, and a facet for it as well. The facet is frequency-order descending. When I click show more in the facet, I get items in asc item-order, not in desc frequency-order. The app is using ml-search-ng 0.2.1.

I am sure I have seen this work in an older version. I think I ran tests with 0.0.12? Maybe facet-options get lost due to recent changes?

**Comment by joemfb** [comment]
The `constraint` to `values` definition transformation probably needs a more detailed test case.

**Comment by grtjn** [comment]
In the request to /v1/values I see:

```
values: [{name: "tag",…}]
  0: {name: "tag",…}
    name: "tag"
    range: {type: "xs:string", facet: true, collation: "http://marklogic.com/collation/codepoint",…}
      collation: "http://marklogic.com/collation/codepoint"
      facet: true
      facet-option: ["limit=5", "frequency-order", "descending"]
      path-index: {text: "tags"}
      type: "xs:string"
```

That is lacking values-option array. But the code looks correct:

```
  function valueOptionsFromConstraint(constraint) {
    var options = { constraint: asArray(constraint), values: asArray(_.cloneDeep(constraint)) };
    options.values['values-option'] = constraint.range && constraint.range['facet-option'];
    return options;
  }
```

No wait, above code makes a mistake. options.values is an array. I think it should be options.values[0]['values-option']..

Yep, tried patching ml-search locally, and that `[0]` did the trick!

**Comment by joemfb** [comment]
Wow, I guess I broke that adding `asArray()` in the last release. I'm really surprised that wasn't caught by a test. I'll rectify that now.

**Comment by joemfb** [comment]
I just pushed the fix (and a test) to master. I'll do a patch release later today.
