### ISSUE TITLE
combined.search.qtext can't be null

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#82]
MarkLogic REST api complains about being unable to parse a combined query if combined.search.query is null. I added the following line to the values function to bypass the message (right before `return mlRest.values`):

```
      combined.search.qtext = combined.search.qtext || '';
```

I noticed this when trying to enable show-more on my ml-github-search project. Perhaps that property should default to the empty string?

**Comment by joemfb** [comment]
I think you're right about the default qtext value, but I think that null is checked a bunch of places. In any case, the query-builder should be more robust to this input.

I've released ml-commong-ng@v0.2.1 with a fix.

**Comment by grtjn** [comment]
Thnx, whatever you changed, it worked..
