### ISSUE TITLE
Don't show 'show more' for custom constraints

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#85]
I don't think values endpoint works well with custom constraints. From the looks of it, you cannot provide custom code for values at all. We already made a change to `annotateActiveFacets` to exclude `bucketed` facets. Exclude `custom` there as well..

**Comment by joemfb** [comment]
Yeah, that's a good point. Maybe we should be doing adhoc searches for every showMoreFacet request?

**Comment by grtjn** [comment]
As a means to by-pass limitations of values? Might work. But until then... ;-)

**Comment by grtjn** [comment]
Related to #74..
