### ISSUE TITLE
Showing tooltip for truncated facet values..

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#91]
Sometimes you have similar looking facet values, that become indistinguishable when truncated. Would be nice if the full value could be shown in a tooltip. Old-school title on anchor, or bootstrap popover?

**Comment by joemfb** [comment]
The full title actually is in a `title` attribute in both templates. It looks correct in `ml-facets-inline.html`, but, somehow, is only on the buttons for `ml-facets.html`. An easy fix in a custom template...

Pull-requests welcome!

**Comment by grtjn** [comment]
Hoping to find some time for PR's soon, but bit tied up at the moment..
