### ISSUE TITLE
resultClick callback instead of resultLink function

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#92]
Having a function that is called when a result is clicked would be more flexible than passing in a (calculated) link to call. Slush uses states for instance, and in some occasions, one might not want to jump away at all, but show an infobox only perhaps.

How about adding an optional result-click attribute on ml-results, and having the template do an ng-click. The default for result-click could be to change $location to result.link..

**Comment by joemfb** [comment]
I like using `ng-href` for the default use-case, since it preserves browser link-handling behaviors, but I see an infobox as a valid use-case for `ng-click`. I guess the directive could branch based on the presence of a `result-click` attribute, or something like that. How does that sound?

**Comment by grtjn** [comment]
Not sure I fully understand 'preserves browser link-handling behaviors'. Do you mean graceful decay if JS is not supported? If not, isn't changing $location effectively the same as clicking a real link?

Anyhow, supporting both `result-link` and `result-click` makes sense. The result-click won't need a default then..

**Comment by joemfb** [comment]
These are client side frameworks; unfortunately, there is no graceful degradation (maybe someday we'll use isomorphic react or ember).

Both `ng-href` and `ui-sref` create actual `href` attributes for you, so mousing over a link shows the target in the browser status bar, cmd+click (OS X) opens in a new tab, etc. The experience matches the basic behavior of links in the browser. On the other hand, the `$location` service is the equivalent of setting `window.location` in VanillaJS; none of the typical affordance for links are shown by the browser.

I'll look into extending the directive.

**Comment by grtjn** [comment]
Thnx for explain, clear now..

**Comment by joemfb** [comment]
I've added a PR implementing my proposal. Let me know if it's suitable for you.

**Comment by grtjn** [comment]
Yep, looks great!

**Comment by grtjn** [comment]
(haven't tried though..)

**Comment by joemfb** [comment]
I've tested it, I just want to confirm that the design works for you. Thanks!
