### ISSUE TITLE
ml-results template can't handle falsy `highlight` values

### ISSUE THREAD

**Issue by joemfb** [joemfb/ml-search-ng#94]
if a highlight property, the `ml-results` template will output the JSON object containing the property. Here's the fix:

    <span ng-class="{ highlight: text.highlight !== undefined }">
      <span ng-if="text.highlight !== undefined">{{ text.highlight }}</span>
      <span ng-if="text.highlight === undefined">{{ text }}</span>
    </span>

**Comment by grtjn** [comment]
sounds familiar.. :)

**Comment by grtjn** [comment]
ah #67, different but similar..
