### ISSUE TITLE
truncateLength not passed through (correctly) to ml-chiclets

### ISSUE THREAD

**Issue by grtjn** [joemfb/ml-search-ng#95]
The truncate attribute takes a value, not a reference. In ml-facets.html, this:

    truncate="truncateLength"

Should be:

    truncate="{{truncateLength}}"

One could also argue, that you might want to have a slightly less truncateLength for chiclets, as the value gets prepended with the facet name, making it longer. Perhaps ml-chiclet should truncate facetname+value according to that length..

**Comment by joemfb** [comment]
Good find, thanks!

**Comment by grtjn** [comment]
Just a matter of using the features.. :)
